name: CI
on:
  workflow_dispatch:
env:
  DEVELOPER_DIR: /Applications/Xcode.app
jobs:
  build-examples:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build macOS Example
        run: cd Examples/ExampleMacOSApp && xcodebuild -scheme ExampleMacOSApp build -destination "generic/platform=macOS"
      - name: Build iOS Example
        run: cd Examples/ExampleiOSApp && xcodebuild -scheme ExampleiOSApp build -destination "name=iPhone 14 Pro"
