name: CI
on:
  workflow_dispatch:
env:
  DEVELOPER_DIR: /Applications/Xcode.app
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build macOS
        run: xcodebuild -scheme SwiftyCreatives build -destination "generic/platform=macOS"
      - name: Build iOS
        run: xcodebuild -scheme SwiftyCreatives build -destination "generic/platform=iOS"
  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test macOS
        run: xcodebuild -scheme SwiftyCreatives test -destination "platform=macOS,arch=x86_64"
      - name: Test iOS
        run: xcodebuild -scheme SwiftyCreatives test -destination "name=iPhone 14 Pro"
  build-examples:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build macOS Example
        run: cd Examples/ExampleMacOSApp && xcodebuild -scheme ExampleMacOSApp build -destination "generic/platform=macOS"
      - name: Build iOS Example
        run: cd Examples/ExampleiOSApp && xcodebuild -scheme ExampleiOSApp build -destination "name=iPhone 14 Pro"
